FROM alpine:3.20
RUN adduser -D -H -u 10001 app
# The binary is provided by GoReleaser in the build context
COPY onr /usr/local/bin/onr
USER app
WORKDIR /home/app
EXPOSE 3000
ENTRYPOINT ["/usr/local/bin/onr"]
CMD ["--config", "/etc/onr/onr.yaml"]
