syntax "next-router/0.1";

balance_mode "openai" {
  balance_unit USD;
}

balance_mode "deepseek" {
  path "/user/balance";
  balance_path "$.balance_infos[0].total_balance";
  balance_unit CNY;
}

balance_mode "moonshot" {
  path "/v1/users/me/balance";
  balance_path "$.data.available_balance";
  balance_unit CNY;
}

balance_mode "openrouter" {
  path "/v1/credits";
  balance_expr = $.data.total_credits - $.data.total_usage;
  used_path "$.data.total_usage";
  balance_unit USD;
}

balance_mode "siliconflow" {
  path "/v1/user/info";
  balance_path "$.data.totalBalance";
  balance_unit USD;
}
